"""Utility functions for context management and formatting."""

import json
from typing import List, Dict, Any


def compact_research_context(raw_results: List[str], max_length: int = 2000) -> str:
    """
    Compress research results into dense knowledge nuggets.
    This prevents context window overflow.
    """
    nuggets = []
    
    for idx, result in enumerate(raw_results[:5], 1):  # Limit to top 5 results
        # Extract key information and summarize
        truncated = result[:max_length]
        nuggets.append(f"[Source {idx}]\n{truncated}\n")
    
    return "\n---\n".join(nuggets)


def format_research_brief(topic: str, findings: str, sources: List[str]) -> Dict[str, Any]:
    """
    Format research into structured JSON output for the Writer agent.
    """
    return {
        "topic": topic,
        "findings": findings,
        "key_points": extract_key_points(findings),
        "sources": sources,
        "timestamp": "2025-11-29"
    }


def extract_key_points(text: str, max_points: int = 7) -> List[str]:
    """
    Extract key points from research text.
    Simple implementation - can be enhanced with NLP.
    """
    # Split by sentences and take most substantial ones
    sentences = [s.strip() for s in text.split('.') if len(s.strip()) > 50]
    return sentences[:max_points]


def calculate_quality_score(draft: str) -> float:
    """
    Calculate a basic quality score for the draft.
    In a production system, this would be more sophisticated.
    """
    score = 5.0  # Base score
    
    # Check length (1200-1800 words is ideal)
    word_count = len(draft.split())
    if 1200 <= word_count <= 1800:
        score += 2.0
    elif 800 <= word_count < 1200 or 1800 < word_count <= 2500:
        score += 1.0
    
    # Check for headers
    if '##' in draft:
        score += 1.0
    
    # Check for structure
    if '**' in draft or '*' in draft:  # Bold or bullet points
        score += 1.0
    
    # Check for citations/links
    if '[' in draft and ']' in draft and '(' in draft:
        score += 1.0
    
    return min(score, 10.0)


def format_output_article(draft: str, metadata: Dict[str, Any]) -> str:
    """
    Format the final article with metadata.
    """
    output = f"""---
title: {metadata.get('title', 'Untitled')}
author: BlogFlow AI
date: {metadata.get('date', '2025-11-29')}
keywords: {', '.join(metadata.get('keywords', []))}
---

{draft}

---

*This article was generated by BlogFlow AI - An Autonomous Content Publishing Team*
*Research Sources: {len(metadata.get('sources', []))} articles analyzed*
"""
    return output


def sanitize_filename(title: str) -> str:
    """
    Convert title to a safe filename.
    """
    # Remove special characters and replace spaces with hyphens
    safe_name = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_'))
    safe_name = safe_name.replace(' ', '-').lower()
    return safe_name[:100]  # Limit length
